---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/susdas-qe/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-build-service-layout-change-tlot
